// ── Role-to-CSS-class helper ────────────────────────────────────────────

export function roleToClass(role: string): string {
  if (role === 'OWNER') return 'role-owner'
  if (role === 'ADMIN') return 'role-admin'
  return 'role-viewer'
}

// ── Server setting types ────────────────────────────────────────────────

export type SettingType = 'readonly' | 'bool' | 'number' | 'text' | 'select'

export interface Setting {
  key: string
  name: string
  desc: string
  type: SettingType
  value: string | number | boolean
  options?: string[]
}

export interface SettingGroup {
  label: string
  desc: string
  settings: Setting[]
}

// ── Game command types ──────────────────────────────────────────────────

export type CommandPerm = 'operator' | 'admin' | 'server'

export interface GameCommand {
  cmd: string
  desc: string
  perm: CommandPerm
}

// ── Server settings ─────────────────────────────────────────────────────
// Keys match the actual ORMOD: Directive serversettings.json format (Playtest 1.9.0).
// Read-only fields (written by the game, not editable) are marked type: 'readonly'.
export const SERVER_SETTING_GROUPS: SettingGroup[] = [
  // ── 1. General ────────────────────────────────────────────────────────
  {
    label: 'General',
    desc: 'Basic Game Host Settings',
    settings: [
      {
        key: 'WorldName',
        name: 'World Name',
        desc: 'Save folder name for this world (set by -servername flag at launch)',
        type: 'text',
        value: 'New World 412',
      },
      {
        key: 'Description',
        name: 'Description',
        desc: 'Shown in the server browser',
        type: 'text',
        value: 'A New Server',
      },
      {
        key: 'GameType',
        name: 'Game Type',
        desc: 'Server game mode: Cooperative (PvE), PVP, Creative, or Arena',
        type: 'select',
        value: 'Cooperative',
        options: ['Cooperative', 'PVP', 'Creative', 'Arena'],
      },
      {
        key: 'IsOnline',
        name: 'Server Browser',
        desc: 'List this server in the public browser',
        type: 'bool',
        value: true,
      },
      {
        key: 'IsWhitelisted',
        name: 'Whitelisted',
        desc: 'Only players on the whitelist can join',
        type: 'bool',
        value: false,
      },
      {
        key: 'FriendsOnly',
        name: 'Friends Only',
        desc: 'Only Steam friends of the host can join',
        type: 'bool',
        value: true,
      },
      {
        key: 'MaxPlayers',
        name: 'Max Players',
        desc: 'Maximum concurrent player slots',
        type: 'number',
        value: 8,
      },
      {
        key: 'IsHardcore',
        name: 'Hardcore Mode',
        desc: 'Enable hardcore mode for increased difficulty and permadeath mechanics',
        type: 'bool',
        value: false,
      },
      {
        key: 'SaveInterval',
        name: 'Save Interval',
        desc: 'How often the world auto-saves, in seconds',
        type: 'number',
        value: 120,
      },
      {
        key: 'LimitMapSize',
        name: 'Limit Map Size',
        desc: 'Cap the playable map area to the value set in Map Size Limit',
        type: 'bool',
        value: false,
      },
      {
        key: 'MapSizeLimit',
        name: 'Map Size Limit',
        desc: 'Maximum map radius in metres when Limit Map Size is enabled',
        type: 'number',
        value: 4000,
      },
      {
        key: 'SpawnRegionSize',
        name: 'Spawn Region Size',
        desc: 'Radius of the initial player spawn region at world centre',
        type: 'number',
        value: 500,
      },
    ],
  },

  // ── 2. Server ─────────────────────────────────────────────────────────
  {
    label: 'Server',
    desc: 'Hidden Configuration Settings',
    settings: [
      {
        key: 'LastPlayedTime',
        name: 'Last Played Time',
        desc: 'Timestamp of the last play session — written by the game binary',
        type: 'readonly',
        value: 639068598923223971,
      },
      {
        key: 'ServerWipeTime',
        name: 'Server Wipe Time',
        desc: 'Timestamp of the last wipe — written by the game binary',
        type: 'readonly',
        value: 639064194977220281,
      },
      {
        key: 'TotalEntityCount',
        name: 'Total Entity Count',
        desc: 'Total number of active entities in the world — updated at runtime',
        type: 'readonly',
        value: 7313,
      },
      {
        key: 'TotalObjectCount',
        name: 'Total Object Count',
        desc: 'Total number of world objects — updated at runtime',
        type: 'readonly',
        value: 331036,
      },
      {
        key: 'ServerVersion',
        name: 'Server Version',
        desc: 'Game build version — set by the server binary',
        type: 'readonly',
        value: '1.8.0',
      },
      {
        key: 'ServerGamePort',
        name: 'Game Port',
        desc: 'UDP port the game listens on — configured in serversettings.json',
        type: 'readonly',
        value: 27015,
      },
      {
        key: 'ServerQueryPort',
        name: 'Query Port',
        desc: 'UDP Steam query port — configured in serversettings.json',
        type: 'readonly',
        value: 27016,
      },
    ],
  },

  // ── 3. World ──────────────────────────────────────────────────────────
  {
    label: 'World',
    desc: 'How The World Topology & Biomes Generate',
    settings: [
      {
        key: 'WorldSeed',
        name: 'World Seed',
        desc: 'Seed string used for procedural world generation',
        type: 'text',
        value: '1627533',
      },
      {
        key: 'StaticMap',
        name: 'Static Map',
        desc: 'Use a fixed pre-authored map instead of procedural generation',
        type: 'bool',
        value: false,
      },
      {
        key: 'WaterHeight',
        name: 'Water Height',
        desc: 'Global sea level height for the world',
        type: 'number',
        value: 7.0,
      },
      {
        key: 'OverallTerrainHeight',
        name: 'Overall Terrain Height',
        desc: 'Global multiplier for terrain elevation across the world',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'BiomeSize',
        name: 'Biome Size',
        desc: 'Multiplier controlling how large each biome region is',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'WorldBiomeTemperature',
        name: 'World Biome Temperature Offset',
        desc: 'Global temperature offset applied across all biomes',
        type: 'number',
        value: 0.0,
      },
      {
        key: 'BiomeBlendingPercentage',
        name: 'Biome Blending',
        desc: 'How much biomes blend into each other at their borders (0–1)',
        type: 'number',
        value: 0.05,
      },
      {
        key: 'TundraSize',
        name: 'Tundra Size',
        desc: 'Relative size multiplier of the Tundra biome',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'TundraLootStage',
        name: 'Tundra Loot Stage',
        desc: 'Base loot tier for the Tundra biome (higher = better loot)',
        type: 'number',
        value: 0.85,
      },
      {
        key: 'TundraTemperature',
        name: 'Tundra Temperature',
        desc: 'Baseline ambient temperature (°C) in the Tundra biome',
        type: 'number',
        value: -10.0,
      },
      {
        key: 'ColdSize',
        name: 'Cold Biome Size',
        desc: 'Relative size multiplier of the Cold biome',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'ColdLootStage',
        name: 'Cold Biome Loot Stage',
        desc: 'Base loot tier for the Cold biome',
        type: 'number',
        value: 0.5,
      },
      {
        key: 'ColdTemperature',
        name: 'Cold Biome Temperature',
        desc: 'Baseline ambient temperature (°C) in the Cold biome',
        type: 'number',
        value: 5.0,
      },
      {
        key: 'TemperateSize',
        name: 'Temperate Biome Size',
        desc: 'Relative size multiplier of the Temperate biome',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'TemperateLootStage',
        name: 'Temperate Biome Loot Stage',
        desc: 'Base loot tier for the Temperate biome',
        type: 'number',
        value: 0.1,
      },
      {
        key: 'TemperateTemperature',
        name: 'Temperate Biome Temperature',
        desc: 'Baseline ambient temperature (°C) in the Temperate biome',
        type: 'number',
        value: 20.0,
      },
      {
        key: 'WarmSize',
        name: 'Warm Biome Size',
        desc: 'Relative size multiplier of the Warm biome',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'WarmLootStage',
        name: 'Warm Biome Loot Stage',
        desc: 'Base loot tier for the Warm biome',
        type: 'number',
        value: 0.55,
      },
      {
        key: 'WarmTemperature',
        name: 'Warm Biome Temperature',
        desc: 'Baseline ambient temperature (°C) in the Warm biome',
        type: 'number',
        value: 35.0,
      },
      {
        key: 'DesertSize',
        name: 'Desert Biome Size',
        desc: 'Relative size multiplier of the Desert biome',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'DesertLootStage',
        name: 'Desert Biome Loot Stage',
        desc: 'Base loot tier for the Desert biome',
        type: 'number',
        value: 0.8,
      },
      {
        key: 'DesertTemperature',
        name: 'Desert Biome Temperature',
        desc: 'Baseline ambient temperature (°C) in the Desert biome',
        type: 'number',
        value: 50.0,
      },
      {
        key: 'CliffSize',
        name: 'Cliff Size',
        desc: 'Multiplier controlling the scale of cliff formations in the world',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'FlatnessScale',
        name: 'Flatness Scale',
        desc: 'Controls how flat or hilly the overall terrain is',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'TerrainMicroBumpScale',
        name: 'Micro Bump Scale',
        desc: 'Scale of small-detail terrain surface bumps',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'TerrainMicroBumpMaxHeight',
        name: 'Micro Bump Max Height',
        desc: 'Maximum height of micro-scale terrain bumps',
        type: 'number',
        value: 5.0,
      },
      {
        key: 'TerrainMicroBumpRigid',
        name: 'Micro Bump Rigid',
        desc: 'Use rigid (sharp-edged) micro bump shapes instead of smooth',
        type: 'bool',
        value: false,
      },
      {
        key: 'TerrainGeneralBumpScale',
        name: 'General Bump Scale',
        desc: 'Scale of medium-detail terrain surface bumps',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'TerrainGeneralBumpMaxHeight',
        name: 'General Bump Max Height',
        desc: 'Maximum height of general-scale terrain bumps',
        type: 'number',
        value: 7.0,
      },
      {
        key: 'TerrainGeneralBumpRigid',
        name: 'General Bump Rigid',
        desc: 'Use rigid (sharp-edged) general bump shapes instead of smooth',
        type: 'bool',
        value: true,
      },
      {
        key: 'TerrainExtremeBumpScale',
        name: 'Extreme Bump Scale',
        desc: 'Scale of large dramatic terrain features such as mountains',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'TerrainExtremeBumpMaxHeight',
        name: 'Extreme Bump Max Height',
        desc: 'Maximum height of extreme-scale terrain features',
        type: 'number',
        value: 150.0,
      },
      {
        key: 'TerrainExtremeBumpRigid',
        name: 'Extreme Bump Rigid',
        desc: 'Use rigid (sharp-edged) extreme terrain feature shapes instead of smooth',
        type: 'bool',
        value: true,
      },
    ],
  },

  // ── 4. Environment ────────────────────────────────────────────────────
  {
    label: 'Environment',
    desc: 'How The World is Populated With Trees, Rocks, Bushes, etc',
    settings: [
      {
        key: 'WorldRegrowthEnabled',
        name: 'World Regrowth',
        desc: 'Allow harvested trees and rocks to regrow over time',
        type: 'bool',
        value: true,
      },
      {
        key: 'WorldRegrowthSpeed',
        name: 'Regrowth Speed',
        desc: 'Multiplier for how quickly harvested world resources regrow',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'GrassDensity',
        name: 'Grass Density',
        desc: 'Density of ground grass across the world',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'GroundLeavesPercentage',
        name: 'Ground Leaves',
        desc: 'Percentage of ground covered in fallen leaves',
        type: 'number',
        value: 0.3,
      },
      {
        key: 'GrassSize',
        name: 'Grass Size',
        desc: 'Scale multiplier for individual grass blades',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'GrassVariation',
        name: 'Grass Variation',
        desc: 'Amount of visual variation applied to grass',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'GrassSpread',
        name: 'Grass Spread',
        desc: 'How widely grass is distributed across terrain',
        type: 'number',
        value: 0.5,
      },
      {
        key: 'ForestWorldPercentage',
        name: 'Forest Coverage',
        desc: 'Proportion of the world covered by forest',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'ForestSize',
        name: 'Forest Size',
        desc: 'Scale multiplier for individual forest patches',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'ForestDensity',
        name: 'Forest Density',
        desc: 'Density of trees within forested areas',
        type: 'number',
        value: 1.1,
      },
      {
        key: 'EdgeThreshold',
        name: 'Edge Threshold',
        desc: 'Distance threshold for forest edge blending with open terrain',
        type: 'number',
        value: 0.05,
      },
      {
        key: 'DebrisDensity',
        name: 'Debris Density',
        desc: 'Density of small environmental debris scattered across the world',
        type: 'number',
        value: 0.05,
      },
      {
        key: 'TreeSpread',
        name: 'Tree Spread',
        desc: 'How widely trees are distributed within forested areas',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RockWorldPercentage',
        name: 'Rock Coverage',
        desc: 'Proportion of the world surface covered by rocks',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RockDensity',
        name: 'Rock Density',
        desc: 'Density of rocks within rocky areas',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RockSpread',
        name: 'Rock Spread',
        desc: 'How widely rocks are distributed across terrain',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'SmallRockClusersPercentage',
        name: 'Small Rock Clusters',
        desc: 'Percentage of rocks that appear as small clusters',
        type: 'number',
        value: 0.1,
      },
      {
        key: 'OrePercentage',
        name: 'Ore Percentage',
        desc: 'Overall proportion of rocks that contain minable ore',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'LowQualityIronDistribution',
        name: 'Low Quality Iron Distribution',
        desc: 'Relative spawn rate of low-quality iron ore nodes',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RefinedIronDistribution',
        name: 'Refined Iron Distribution',
        desc: 'Relative spawn rate of refined iron ore nodes',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'HighQualityIronDistribution',
        name: 'High Quality Iron Distribution',
        desc: 'Relative spawn rate of high-quality iron ore nodes',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RefinedCopperDistribution',
        name: 'Refined Copper Distribution',
        desc: 'Relative spawn rate of refined copper ore nodes',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'HighQualityCopperDistribution',
        name: 'High Quality Copper Distribution',
        desc: 'Relative spawn rate of high-quality copper ore nodes',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'GoldDistribution',
        name: 'Gold Distribution',
        desc: 'Relative spawn rate of gold ore nodes',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'CoalDistribution',
        name: 'Coal Distribution',
        desc: 'Relative spawn rate of coal ore nodes',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'SulpherDistribution',
        name: 'Sulphur Distribution',
        desc: 'Relative spawn rate of sulphur ore nodes',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'BushWorldPercentage',
        name: 'Bush Coverage',
        desc: 'Proportion of the world covered by bushes and shrubs',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'ForestVegitationWorldPercentage',
        name: 'Forest Vegetation Coverage',
        desc: 'Proportion of forested areas that include undergrowth vegetation',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'VegitationDensity',
        name: 'Vegetation Density',
        desc: 'Density of vegetation (bushes, plants) in vegetated areas',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'VegitationSpread',
        name: 'Vegetation Spread',
        desc: 'How widely vegetation is distributed across terrain',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'FlowerWorldPercentage',
        name: 'Flower Coverage',
        desc: 'Proportion of the world covered by flowers',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'FlowerClusterPercentage',
        name: 'Flower Cluster Percentage',
        desc: 'Percentage of flowers that spawn in clusters rather than individually',
        type: 'number',
        value: 0.3,
      },
    ],
  },

  // ── 5. Structures ─────────────────────────────────────────────────────
  {
    label: 'Structures',
    desc: 'Settings For POIs, Towns, Roads, etc',
    settings: [
      {
        key: 'RailRoadSpawnPercentage',
        name: 'Railroad Spawn Chance',
        desc: 'Proportion of the map that includes railroad infrastructure',
        type: 'number',
        value: 0.2,
      },
      {
        key: 'PowerLineSpawnPercentage',
        name: 'Power Line Spawn Chance',
        desc: 'Proportion of the map covered by power line corridors',
        type: 'number',
        value: 0.2,
      },
      {
        key: 'HighwaySpawnPercentage',
        name: 'Highway Spawn Chance',
        desc: 'Proportion of the map that includes highway routes',
        type: 'number',
        value: 0.1,
      },
      {
        key: 'RuralRoadSpawnPercentage',
        name: 'Rural Road Spawn Chance',
        desc: 'Proportion of the map covered by rural roads',
        type: 'number',
        value: 0.4,
      },
      {
        key: 'PathwaPOIAmount',
        name: 'Pathway POI Amount',
        desc: 'Multiplier for the number of points-of-interest connected by pathways',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PathwayCurvyness',
        name: 'Pathway Curviness',
        desc: 'How winding/curved generated pathways between POIs are',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PathwayJunctions',
        name: 'Pathway Junctions',
        desc: 'Multiplier for the number of pathway junctions and intersections',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'StructureDensity',
        name: 'Structure Density',
        desc: 'Overall density of man-made structures across the world',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'GeneralStructureSize',
        name: 'General Structure Size',
        desc: 'Scale multiplier applied to all structure footprints',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'CityPercentage',
        name: 'City Percentage',
        desc: 'Proportion of structures that belong to city districts',
        type: 'number',
        value: 0.1,
      },
      {
        key: 'TownPercentage',
        name: 'Town Percentage',
        desc: 'Proportion of structures that belong to towns',
        type: 'number',
        value: 0.4,
      },
      {
        key: 'TownBaseSize',
        name: 'Town Base Size',
        desc: 'Base radius (metres) of a generated town',
        type: 'number',
        value: 100.0,
      },
      {
        key: 'IndustrialStructures',
        name: 'Industrial Structures',
        desc: 'Relative weight for industrial building types when placing structures',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'ResidentialStructures',
        name: 'Residential Structures',
        desc: 'Relative weight for residential building types',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'MedicalStructures',
        name: 'Medical Structures',
        desc: 'Relative weight for medical building types (hospitals, clinics)',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'MilitaryStructures',
        name: 'Military Structures',
        desc: 'Relative weight for military building types',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'SmallStructures',
        name: 'Small Structures',
        desc: 'Relative weight for small building and shed types',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RuralStructures',
        name: 'Rural Structures',
        desc: 'Relative weight for rural and farmstead building types',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'HighriseStructures',
        name: 'Highrise Structures',
        desc: 'Relative weight for highrise and skyscraper building types',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'TraderStructures',
        name: 'Trader Structures',
        desc: 'Relative weight for trader outpost structures',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'WindFieldsWorldPercentage',
        name: 'Wind Field Coverage',
        desc: 'Proportion of the world that contains wind turbine field structures',
        type: 'number',
        value: 0.25,
      },
    ],
  },

  // ── 6. Loot ───────────────────────────────────────────────────────────
  {
    label: 'Loot',
    desc: 'Loot Spawn Amount, Quality, Respawning, etc',
    settings: [
      {
        key: 'ObjectRespawningEnabled',
        name: 'Object Respawning',
        desc: 'Allow world objects (barrels, crates, etc.) to respawn after being looted',
        type: 'bool',
        value: true,
      },
      {
        key: 'GeneralObjectDensity',
        name: 'General Object Density',
        desc: 'Density of general interactable objects across the world',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'JunkObjectDensity',
        name: 'Junk Object Density',
        desc: 'Density of junk and scrap objects scattered around the world',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'LargeObjectDensity',
        name: 'Large Object Density',
        desc: 'Density of large world objects such as vehicles and machinery',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RandomObjectDensity',
        name: 'Random Object Density',
        desc: 'Density of randomly placed miscellaneous world objects',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'OverallLootModifier',
        name: 'Overall Loot Modifier',
        desc: 'Global multiplier applied to all loot quantities',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'LootZonesModifier',
        name: 'Loot Zones Modifier',
        desc: 'Loot quantity multiplier applied specifically inside designated loot zones',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'ClumpedLootModifier',
        name: 'Clumped Loot Modifier',
        desc: 'Multiplier for loot that spawns in grouped/clumped configurations',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'EarlyGameLootModifier',
        name: 'Early Game Loot Modifier',
        desc: 'Multiplier for early-tier loot item quantities',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'MidGameLootModifier',
        name: 'Mid Game Loot Modifier',
        desc: 'Multiplier for mid-tier loot item quantities',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'LateGameLootModifier',
        name: 'Late Game Loot Modifier',
        desc: 'Multiplier for late-tier (high-end) loot item quantities',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'StructureVarientAffectsLootTier',
        name: 'Structure Variant Affects Loot Tier',
        desc: 'Whether a structure\'s variant/condition influences the quality of its loot',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'LootstageIncrease',
        name: 'Loot Stage Increase',
        desc: 'Rate at which loot stage progresses as players advance',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'WoodGatherRate',
        name: 'Wood Gather Rate',
        desc: 'Multiplier for wood yield when chopping trees',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'ScrappingGatherRate',
        name: 'Scrapping Gather Rate',
        desc: 'Multiplier for materials gained when scrapping objects',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'OreGatherRate',
        name: 'Ore Gather Rate',
        desc: 'Multiplier for ore yield when mining rocks',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'GroundVehicleSpawnrate',
        name: 'Ground Vehicle Spawn Rate',
        desc: 'Multiplier for the number of ground vehicles spawned in the world',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'AirVehicleSpawnrate',
        name: 'Air Vehicle Spawn Rate',
        desc: 'Multiplier for the number of air vehicles spawned in the world',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'ItemDespawnTime',
        name: 'Item Despawn Time',
        desc: 'Time in seconds before dropped items despawn from the world',
        type: 'number',
        value: 1500,
      },
      {
        key: 'LootRespawnEnabled',
        name: 'Loot Respawn',
        desc: 'Allow loot containers to restock after a set time',
        type: 'bool',
        value: true,
      },
      {
        key: 'LootRefreshTime',
        name: 'Loot Refresh Time',
        desc: 'Time in minutes before looted containers are restocked',
        type: 'number',
        value: 30.0,
      },
      {
        key: 'LootRespawnDistance',
        name: 'Loot Respawn Distance',
        desc: 'Minimum distance a player must be from a container for it to respawn',
        type: 'number',
        value: 100.0,
      },
    ],
  },

  // ── 7. Machines ───────────────────────────────────────────────────────
  {
    label: 'Machines',
    desc: 'Mechanoid Spawnrates, Difficulty & Automation Functions',
    settings: [
      {
        key: 'WorldRobotDensity',
        name: 'Robot Density',
        desc: 'Multiplier for ORMOD mechanoid spawn density across the world',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'WorldRobotActivation',
        name: 'World Robot Activation',
        desc: 'Multiplier for the range or threshold at which world robots become active',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RefulingStationAffectWorldActivation',
        name: 'Refueling Station Affects Activation',
        desc: 'Whether refueling stations influence the world robot activation range',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RobotPlating',
        name: 'Robot Plating',
        desc: 'Armour thickness multiplier for mechanoids (1.0 = default)',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RobotDifficulty',
        name: 'Robot Difficulty',
        desc: 'Overall AI difficulty multiplier for mechanoids (1.0 = default)',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RobotViewAngleMultiplier',
        name: 'Robot View Angle',
        desc: 'Multiplier for mechanoid field-of-view detection angle',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RobotStandingStealthMultiplier',
        name: 'Standing Stealth Multiplier',
        desc: 'How detectable a standing player is to mechanoids (lower = harder to spot)',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RobotCrouchStealthMultiplier',
        name: 'Crouching Stealth Multiplier',
        desc: 'How detectable a crouching player is to mechanoids',
        type: 'number',
        value: 0.6,
      },
      {
        key: 'RobotProneStealthMultiplier',
        name: 'Prone Stealth Multiplier',
        desc: 'How detectable a prone player is to mechanoids',
        type: 'number',
        value: 0.3,
      },
      {
        key: 'RobotNightVisionMultiplier',
        name: 'Robot Night Vision',
        desc: 'Multiplier for mechanoid detection ability at night (>1 = better night vision)',
        type: 'number',
        value: 1.2,
      },
      {
        key: 'BiomeAffectsNightAttacks',
        name: 'Biome Affects Night Attacks',
        desc: 'Whether the current biome modifies night-time robot attack intensity',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'NightMinSpawnRadius',
        name: 'Night Min Spawn Radius',
        desc: 'Minimum distance from players at which night-time robots spawn',
        type: 'number',
        value: 40.0,
      },
      {
        key: 'NightMaxSpawnRadius',
        name: 'Night Max Spawn Radius',
        desc: 'Maximum distance from players at which night-time robots spawn',
        type: 'number',
        value: 60.0,
      },
      {
        key: 'NightAttackDifficultyMultiplier',
        name: 'Night Attack Difficulty',
        desc: 'Difficulty multiplier applied to robot attacks during night-time',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'SkuttlerSpeed',
        name: 'Skuttler Speed (Day)',
        desc: 'Movement speed for Skuttler-type mechanoids during daytime',
        type: 'number',
        value: 2,
      },
      {
        key: 'SkuttlerNightSpeed',
        name: 'Skuttler Speed (Night)',
        desc: 'Movement speed for Skuttler-type mechanoids at night — usually faster',
        type: 'number',
        value: 4,
      },
      {
        key: 'WalkerSpeed',
        name: 'Walker Speed',
        desc: 'Movement speed for Walker-type mechanoids',
        type: 'number',
        value: 2,
      },
      {
        key: 'MachineTickRate',
        name: 'Machine Tick Rate',
        desc: 'How frequently automated machines process their production cycle (seconds per tick)',
        type: 'number',
        value: 0.2,
      },
      {
        key: 'MachineSpawnRate',
        name: 'Machine Spawn Rate',
        desc: 'Multiplier for how often machines spawn entities or items',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'UnpoweredMachineProductionRate',
        name: 'Unpowered Production Rate',
        desc: 'Production rate multiplier for machines operating without power',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PoweredMachineProductionRate',
        name: 'Powered Production Rate',
        desc: 'Production rate multiplier for powered machines',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'MachinePowerProduction',
        name: 'Machine Power Production',
        desc: 'Multiplier for the amount of power generators produce',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'MachinePowerUsage',
        name: 'Machine Power Usage',
        desc: 'Multiplier for the amount of power machines consume',
        type: 'number',
        value: 1.0,
      },
    ],
  },

  // ── 8. Weather ────────────────────────────────────────────────────────
  {
    label: 'Weather',
    desc: 'Weather Systems & Effects',
    settings: [
      {
        key: 'DayDuration',
        name: 'Day Duration',
        desc: 'Length of the daytime phase in in-game seconds',
        type: 'number',
        value: 2400,
      },
      {
        key: 'NightDuration',
        name: 'Night Duration',
        desc: 'Length of the night-time phase in in-game seconds',
        type: 'number',
        value: 900,
      },
      {
        key: 'NightTemperatureChangeLow',
        name: 'Night Temperature Change (Low)',
        desc: 'Minimum temperature shift (°C) applied during night-time',
        type: 'number',
        value: -5.0,
      },
      {
        key: 'DayTemperatureChangeHigh',
        name: 'Day Temperature Change (High)',
        desc: 'Maximum temperature shift (°C) applied during daytime',
        type: 'number',
        value: 5.0,
      },
      {
        key: 'ClearPercentage',
        name: 'Clear Weather Chance',
        desc: 'Probability weight for clear weather occurring',
        type: 'number',
        value: 0.225,
      },
      {
        key: 'ClearTemperatureChange',
        name: 'Clear Weather Temperature Change',
        desc: 'Temperature change (°C) applied during clear weather',
        type: 'number',
        value: 5.0,
      },
      {
        key: 'SolarClearModifier',
        name: 'Solar Clear Modifier',
        desc: 'Solar panel efficiency multiplier during clear weather',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'SparsePercentage',
        name: 'Sparse Cloud Chance',
        desc: 'Probability weight for sparse (partly cloudy) weather',
        type: 'number',
        value: 0.25,
      },
      {
        key: 'SparseTemperatureChange',
        name: 'Sparse Weather Temperature Change',
        desc: 'Temperature change (°C) during sparse cloud weather',
        type: 'number',
        value: 5.0,
      },
      {
        key: 'SolarSparseModifier',
        name: 'Solar Sparse Modifier',
        desc: 'Solar panel efficiency multiplier during sparse cloud weather',
        type: 'number',
        value: 0.9,
      },
      {
        key: 'CloudyPercentage',
        name: 'Cloudy Weather Chance',
        desc: 'Probability weight for cloudy weather',
        type: 'number',
        value: 0.25,
      },
      {
        key: 'CloudyTemperatureChange',
        name: 'Cloudy Weather Temperature Change',
        desc: 'Temperature change (°C) during cloudy weather',
        type: 'number',
        value: 0.0,
      },
      {
        key: 'SolarCloudyModifier',
        name: 'Solar Cloudy Modifier',
        desc: 'Solar panel efficiency multiplier during cloudy weather',
        type: 'number',
        value: 0.8,
      },
      {
        key: 'OvercastPercentage',
        name: 'Overcast Weather Chance',
        desc: 'Probability weight for overcast (heavy cloud) weather',
        type: 'number',
        value: 0.1,
      },
      {
        key: 'OvercastTemperatureChange',
        name: 'Overcast Weather Temperature Change',
        desc: 'Temperature change (°C) during overcast weather',
        type: 'number',
        value: -5.0,
      },
      {
        key: 'SolarOvercastModifier',
        name: 'Solar Overcast Modifier',
        desc: 'Solar panel efficiency multiplier during overcast weather',
        type: 'number',
        value: 0.5,
      },
      {
        key: 'LightRainPercentage',
        name: 'Light Rain Chance',
        desc: 'Probability weight for light rain weather',
        type: 'number',
        value: 0.075,
      },
      {
        key: 'LightRainTemperatureChange',
        name: 'Light Rain Temperature Change',
        desc: 'Temperature change (°C) during light rain',
        type: 'number',
        value: -10.0,
      },
      {
        key: 'SolarLightRainModifier',
        name: 'Solar Light Rain Modifier',
        desc: 'Solar panel efficiency multiplier during light rain',
        type: 'number',
        value: 0.6,
      },
      {
        key: 'StormPercentage',
        name: 'Storm Chance',
        desc: 'Probability weight for stormy weather',
        type: 'number',
        value: 0.05,
      },
      {
        key: 'StormyTemperatureChange',
        name: 'Storm Temperature Change',
        desc: 'Temperature change (°C) during a storm',
        type: 'number',
        value: -20.0,
      },
      {
        key: 'SolarStormyModifier',
        name: 'Solar Storm Modifier',
        desc: 'Solar panel efficiency multiplier during stormy weather',
        type: 'number',
        value: 0.4,
      },
      {
        key: 'LightningStormPercentage',
        name: 'Lightning Storm Chance',
        desc: 'Probability weight for lightning storm weather',
        type: 'number',
        value: 0.05,
      },
      {
        key: 'LightningTemperatureChange',
        name: 'Lightning Storm Temperature Change',
        desc: 'Temperature change (°C) during a lightning storm',
        type: 'number',
        value: -20.0,
      },
      {
        key: 'SolarLightningModifier',
        name: 'Solar Lightning Modifier',
        desc: 'Solar panel efficiency multiplier during a lightning storm',
        type: 'number',
        value: 0.3,
      },
      {
        key: 'LightningMinIntervall',
        name: 'Lightning Min Interval',
        desc: 'Minimum time in seconds between lightning strikes during a storm',
        type: 'number',
        value: 2.0,
      },
      {
        key: 'LightningMaxIntervall',
        name: 'Lightning Max Interval',
        desc: 'Maximum time in seconds between lightning strikes during a storm',
        type: 'number',
        value: 8.0,
      },
      {
        key: 'FogPercentage',
        name: 'Fog Chance',
        desc: 'Probability weight for foggy conditions',
        type: 'number',
        value: 0.2,
      },
      {
        key: 'FogTemperatureChange',
        name: 'Fog Temperature Change',
        desc: 'Temperature change (°C) during fog',
        type: 'number',
        value: -5.0,
      },
      {
        key: 'FoggynessModifier',
        name: 'Foggy-ness Modifier',
        desc: 'Density multiplier for fog — higher values create thicker fog',
        type: 'number',
        value: 1.0,
      },
    ],
  },

  // ── 9. Trader ─────────────────────────────────────────────────────────
  {
    label: 'Trader',
    desc: 'Trading, Quests & Global Events Settings',
    settings: [
      {
        key: 'ItemSellModifier',
        name: 'Item Sell Modifier',
        desc: 'Multiplier applied to the price players receive when selling items to traders',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'ItemBuyModifier',
        name: 'Item Buy Modifier',
        desc: 'Multiplier applied to the price players pay when buying items from traders',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'MinTraderDistance',
        name: 'Min Trader Distance',
        desc: 'Minimum distance (metres) between trader outpost spawn locations',
        type: 'number',
        value: 1250,
      },
      {
        key: 'QuestLocationRange',
        name: 'Quest Location Range',
        desc: 'Maximum distance (metres) at which quest objectives can be generated from the trader',
        type: 'number',
        value: 500,
      },
      {
        key: 'QuestRewardModifier',
        name: 'Quest Reward Modifier',
        desc: 'Multiplier applied to rewards granted upon completing quests',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'QuestTimeLimit',
        name: 'Quest Time Limit',
        desc: 'Time limit in minutes that players have to complete a quest',
        type: 'number',
        value: 30,
      },
      {
        key: 'NumberOfQuestsGeneratedPerDay',
        name: 'Quests Generated Per Day',
        desc: 'Number of new quests generated and available at traders each in-game day',
        type: 'number',
        value: 3,
      },
      {
        key: 'TraderQuestTierModifier',
        name: 'Trader Quest Tier Modifier',
        desc: 'Multiplier that shifts the tier (difficulty) of generated trader quests',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'GenerateRandomQuests',
        name: 'Generate Random Quests',
        desc: 'Allow the server to generate procedural random quests',
        type: 'bool',
        value: true,
      },
      {
        key: 'MinimumStartRandomQuestTime',
        name: 'Min Random Quest Start Time',
        desc: 'Minimum in-game time (seconds) before a random quest can begin',
        type: 'number',
        value: 1800,
      },
      {
        key: 'MaximumStartRandomQuestTime',
        name: 'Max Random Quest Start Time',
        desc: 'Maximum in-game time (seconds) before a random quest can begin',
        type: 'number',
        value: 3600,
      },
      {
        key: 'MaximumOngoingQuests',
        name: 'Maximum Ongoing Quests',
        desc: 'Maximum number of quests a player can have active simultaneously',
        type: 'number',
        value: 2,
      },
      {
        key: 'QuestEasyAllowed',
        name: 'Easy Quests Allowed',
        desc: 'Allow easy-tier quests to be generated',
        type: 'bool',
        value: true,
      },
      {
        key: 'QuestMediumAllowed',
        name: 'Medium Quests Allowed',
        desc: 'Allow medium-tier quests to be generated',
        type: 'bool',
        value: true,
      },
      {
        key: 'QuestHardAllowed',
        name: 'Hard Quests Allowed',
        desc: 'Allow hard-tier quests to be generated',
        type: 'bool',
        value: true,
      },
      {
        key: 'RandomWorldEventSpawnPercentage',
        name: 'Random World Event Spawn Chance',
        desc: 'Probability that a random world event spawns during a given period',
        type: 'number',
        value: 0.15,
      },
      {
        key: 'RandomRoadEventSpawnPercentage',
        name: 'Random Road Event Spawn Chance',
        desc: 'Probability that a random event spawns along roads',
        type: 'number',
        value: 0.3,
      },
    ],
  },

  // ── 10. Player ────────────────────────────────────────────────────────
  {
    label: 'Player',
    desc: 'Player Modifiers Including Health, Speed, etc',
    settings: [
      {
        key: 'PlayerMaxHealth',
        name: 'Max Health',
        desc: 'Maximum health points a player can have',
        type: 'number',
        value: 100.0,
      },
      {
        key: 'PlayerMaxFood',
        name: 'Max Food',
        desc: 'Maximum food saturation value for a player',
        type: 'number',
        value: 5000.0,
      },
      {
        key: 'PlayerMaxWater',
        name: 'Max Water',
        desc: 'Maximum hydration value for a player',
        type: 'number',
        value: 5.0,
      },
      {
        key: 'SkillPointsAtStart',
        name: 'Starting Skill Points',
        desc: 'Number of skill points granted to a player at character creation',
        type: 'number',
        value: 1,
      },
      {
        key: 'PlayerXPCollected',
        name: 'XP Collected Multiplier',
        desc: 'Multiplier for all experience points gained by players',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerWalkSpeed',
        name: 'Walk Speed',
        desc: 'Multiplier for player walking movement speed',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerRunSpeed',
        name: 'Run Speed',
        desc: 'Multiplier for player running movement speed',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerDamageTaken',
        name: 'Damage Taken Multiplier',
        desc: 'Multiplier for all incoming damage received by players',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerDamageGiven',
        name: 'Damage Given Multiplier',
        desc: 'Multiplier for all outgoing damage dealt by players',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerVicinityChatMaxtDistance',
        name: 'Vicinity Chat Max Distance',
        desc: 'Maximum distance (metres) at which players can hear vicinity chat',
        type: 'number',
        value: 50.0,
      },
      {
        key: 'CarryWeightModifier',
        name: 'Carry Weight Modifier',
        desc: 'Multiplier for player carry weight capacity',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerStaminaDrain',
        name: 'Stamina Drain',
        desc: 'Multiplier for how quickly player stamina depletes during exertion',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerFoodDrain',
        name: 'Food Drain',
        desc: 'Multiplier for the rate at which player hunger decreases over time',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerWaterDrain',
        name: 'Water Drain',
        desc: 'Multiplier for the rate at which player thirst decreases over time',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerFoodWaterDamageModifier',
        name: 'Food/Water Damage Modifier',
        desc: 'Multiplier for damage taken when starving or dehydrated',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerFoodWaterDamagePercentage',
        name: 'Food/Water Damage Percentage',
        desc: 'Percentage of max health lost per tick when starving or dehydrated',
        type: 'number',
        value: 0.1,
      },
      {
        key: 'PlayerTemperatureExposure',
        name: 'Temperature Exposure',
        desc: 'Multiplier for how strongly ambient temperature affects the player',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerOverheatTemperature',
        name: 'Overheat Temperature',
        desc: 'Ambient temperature (°C) above which the player begins overheating',
        type: 'number',
        value: 35.0,
      },
      {
        key: 'PlayerFreezeTemperature',
        name: 'Freeze Temperature',
        desc: 'Ambient temperature (°C) below which the player begins freezing',
        type: 'number',
        value: 5.0,
      },
      {
        key: 'PlayerTemperatureDamageModifier',
        name: 'Temperature Damage Modifier',
        desc: 'Multiplier for damage taken from extreme temperature exposure',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'PlayerMovementTemperatureChange',
        name: 'Movement Temperature Change',
        desc: 'How much player movement (running, sprinting) affects perceived body temperature',
        type: 'number',
        value: 2.0,
      },
      {
        key: 'RaidingEnabled',
        name: 'Raiding Enabled',
        desc: 'Allow players to raid (destroy structures of) other players',
        type: 'bool',
        value: true,
      },
      {
        key: 'RaidingModifier',
        name: 'Raiding Modifier',
        desc: 'Multiplier for damage dealt to player-built structures during raids',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'RaidingOfflineModifier',
        name: 'Offline Raiding Modifier',
        desc: 'Multiplier for structure damage when the defending player is offline',
        type: 'number',
        value: 0.3,
      },
      {
        key: 'PlayerStatusEffectTime',
        name: 'Status Effect Duration',
        desc: 'Multiplier for the duration of status effects (buffs and debuffs) on players',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'MinInflictBleedDamage',
        name: 'Min Bleed Damage',
        desc: 'Minimum damage dealt per tick by a bleed status effect',
        type: 'number',
        value: 10.0,
      },
      {
        key: 'MaxInflictBleedDamage',
        name: 'Max Bleed Damage',
        desc: 'Maximum damage dealt per tick by a bleed status effect',
        type: 'number',
        value: 45.0,
      },
      {
        key: 'MinInflictHeavyBleedDamage',
        name: 'Min Heavy Bleed Damage',
        desc: 'Minimum damage dealt per tick by a heavy bleed status effect',
        type: 'number',
        value: 20.0,
      },
      {
        key: 'MaxInflictHeavyBleedDamage',
        name: 'Max Heavy Bleed Damage',
        desc: 'Maximum damage dealt per tick by a heavy bleed status effect',
        type: 'number',
        value: 65.0,
      },
      {
        key: 'BleedDamagePercentage',
        name: 'Bleed Damage Percentage',
        desc: 'Percentage of max health that bleed damage can remove per tick',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'HeavyBleedDamagePercentage',
        name: 'Heavy Bleed Damage Percentage',
        desc: 'Percentage of max health that heavy bleed damage can remove per tick',
        type: 'number',
        value: 3.0,
      },
      {
        key: 'SicknessModifier',
        name: 'Sickness Modifier',
        desc: 'Multiplier for the severity of sickness effects on players',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'DiseaseCatchModifier',
        name: 'Disease Catch Modifier',
        desc: 'Multiplier for how easily players catch diseases from environmental exposure',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'DiseaseProgressionModifier',
        name: 'Disease Progression Modifier',
        desc: 'Multiplier for how quickly diseases progress if left untreated',
        type: 'number',
        value: 1.0,
      },
      {
        key: 'StartPositionRange',
        name: 'Start Position Range',
        desc: 'Radius (metres) around the world centre within which new players can spawn',
        type: 'number',
        value: 1000,
      },
      {
        key: 'StartingItemTier',
        name: 'Starting Item Tier',
        desc: 'Tier level of the items players receive when they first spawn',
        type: 'number',
        value: 1,
      },
      {
        key: 'StartingMoney',
        name: 'Starting Money',
        desc: 'Amount of currency players start with upon first spawning',
        type: 'number',
        value: 100,
      },
      {
        key: 'StartingItems',
        name: 'Starting Items',
        desc: 'Comma-separated list of item IDs given to players when they first spawn',
        type: 'text',
        value: 'apple, bandage_low',
      },
      {
        key: 'WorldOvergrowth',
        name: 'World Overgrowth',
        desc: 'Degree to which post-apocalyptic overgrowth (vines, moss) covers world structures',
        type: 'number',
        value: 0.4,
      },
    ],
  },
]

// ── Console quick commands ──────────────────────────────────────────────
// Full reference: docs/game-commands.md
export const GAME_COMMANDS: GameCommand[] = [
  // [server]
  { cmd: 'forcesave', desc: 'Force world save', perm: 'server' },
  { cmd: 'setserversetting [setting] [value]', desc: 'Set a server setting', perm: 'server' },
  { cmd: 'setpermissions [steamId] [level]', desc: 'Set player permission level', perm: 'server' },
  { cmd: 'removepermissions [steamId]', desc: 'Remove player permissions', perm: 'server' },
  { cmd: 'authenabled [true/false]', desc: 'Enable/disable serverside auth', perm: 'server' },
  { cmd: 'anticheatenabled [true/false]', desc: 'Enable/disable anticheat', perm: 'server' },
  // [admin]
  { cmd: 'getserversettings', desc: 'Show all current server settings', perm: 'admin' },
  { cmd: 'ban [steamId]', desc: 'Ban a player', perm: 'admin' },
  { cmd: 'unban [steamId]', desc: 'Unban a player', perm: 'admin' },
  { cmd: 'whitelist [steamId]', desc: 'Whitelist a player', perm: 'admin' },
  { cmd: 'removewhitelist [steamId]', desc: 'Remove player from whitelist', perm: 'admin' },
  { cmd: 'kill [steamId]', desc: 'Kill a player', perm: 'admin' },
  { cmd: 'killall', desc: 'Kill all players', perm: 'admin' },
  { cmd: 'teleport [steamId]', desc: 'Teleport self to player', perm: 'admin' },
  { cmd: 'teleport [from] [to]', desc: 'Teleport one player to another', perm: 'admin' },
  { cmd: 'teleport [x] [y] [z]', desc: 'Teleport self to coordinates', perm: 'admin' },
  { cmd: 'teleport [steamId] [x] [y] [z]', desc: 'Teleport player to coordinates', perm: 'admin' },
  { cmd: 'settime [0000-2400]', desc: 'Set world time', perm: 'admin' },
  { cmd: 'setweather [type]', desc: 'cloudy/stormy/overcast/sparse/clear/lightningstorm/lightrain', perm: 'admin' },
  { cmd: 'setfog [true/false]', desc: 'Toggle world fog', perm: 'admin' },
  { cmd: 'setammo [true/false]', desc: 'Weapons & turrets use ammo', perm: 'admin' },
  { cmd: 'spawn [entity]', desc: 'Spawn entity here', perm: 'admin' },
  { cmd: 'spawn [entity] [steamId]', desc: 'Spawn entity at player', perm: 'admin' },
  { cmd: 'godmode', desc: 'Toggle self godmode', perm: 'admin' },
  { cmd: 'godmode [steamId] [true/false]', desc: 'Set player godmode', perm: 'admin' },
  { cmd: 'noclip', desc: 'Toggle self noclip', perm: 'admin' },
  { cmd: 'noclip [steamId] [true/false]', desc: 'Set player noclip', perm: 'admin' },
  { cmd: 'spectator', desc: 'Toggle self spectator', perm: 'admin' },
  { cmd: 'spectator [steamId] [true/false]', desc: 'Set player spectator', perm: 'admin' },
  { cmd: 'forcerespawnloot', desc: 'Force respawn all loot pools', perm: 'admin' },
  { cmd: 'enabletracers [true/false]', desc: 'Enable/disable tracers', perm: 'admin' },
  { cmd: 'setdata [entityId] [key] [value]', desc: 'Set entity data tag', perm: 'admin' },
  // [operator]
  { cmd: 'getplayers', desc: 'List all players on server', perm: 'operator' },
  { cmd: 'announcement [message]', desc: 'Send chat announcement to all players', perm: 'operator' },
  { cmd: 'kick [steamId]', desc: 'Kick a player', perm: 'operator' },
  { cmd: 'heal [steamId]', desc: 'Reset all stats of player', perm: 'operator' },
  { cmd: 'heal', desc: 'Reset all stats of self', perm: 'operator' },
  { cmd: 'addxp [steamId] [amount]', desc: 'Add XP to player', perm: 'operator' },
  { cmd: 'addxp [amount]', desc: 'Add XP to self', perm: 'operator' },
  { cmd: 'addeffect [steamId] [stat] [dur] [amt]', desc: 'Add effect to player', perm: 'operator' },
  { cmd: 'removeeffect [steamId] [stat]', desc: 'Remove effect from player', perm: 'operator' },
  { cmd: 'cleareffects [steamId]', desc: 'Clear all effects from player', perm: 'operator' },
  { cmd: 'unlockallskills [steamId]', desc: 'Unlock all skills for player', perm: 'operator' },
  { cmd: 'unlockallblueprints [steamId]', desc: 'Unlock all blueprints for player', perm: 'operator' },
  { cmd: 'getlocation', desc: 'Get current location', perm: 'operator' },
  { cmd: 'seed', desc: 'Get current location and seed', perm: 'operator' },
  { cmd: 'getentity', desc: 'Get looking-at entity ID', perm: 'operator' },
  { cmd: 'getbiome', desc: 'Get current biome', perm: 'operator' },
  { cmd: 'setteam [steamId] [teamnumber]', desc: 'Set player arena team', perm: 'operator' },
  { cmd: 'setteamspawn [teamnumber]', desc: 'Set arena team spawn here', perm: 'operator' },
  { cmd: 'startmatch', desc: 'Start new arena match', perm: 'operator' },
  { cmd: 'getallkits', desc: 'Get all kits on server', perm: 'operator' },
]
